# AWS CloudFormation template for Elastic Beanstalk deployment
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI-Powered Anomaly Detection Dashboard on AWS Elastic Beanstalk'

Parameters:
  ApplicationName:
    Type: String
    Default: anomaly-detection-dashboard
    Description: Name of the Elastic Beanstalk application
  
  EnvironmentName:
    Type: String
    Default: anomaly-detection-prod
    Description: Name of the Elastic Beanstalk environment

Resources:
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: AI-Powered Anomaly Detection Dashboard

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: 64bit Amazon Linux 2 v3.4.16 running Python 3.11
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t3.medium
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: '1'
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: '3'
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: STREAMLIT_SERVER_HEADLESS
          Value: 'true'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: STREAMLIT_SERVER_PORT
          Value: '8501'

Outputs:
  URL:
    Description: URL of the deployed application
    Value: !GetAtt Environment.EndpointURL
    Export:
      Name: !Sub '${AWS::StackName}-URL'
